### ISSUE TITLE
pywinauto.findwindows.ElementNotFoundError

### ISSUE THREAD

**Issue by wdl5i** [nladuo/THSTrader#11]
我在win10的环境下，用楼主百度网盘中提供的同花顺软件，运行不起来，具体表现：
1. pandas指定的0.23.0版本安装不了，最低版本可安装0.24.2，该软件版本差异应该不影响使用
2. pywinauto中的SendKeys应该替换为send_keys, 之前使用的是一个已废弃的api, 不影响使用
3. 运行test.py, 能正常连接同花顺客户端，之后获取可用资金失败，猜测可能是该程序与百度云中的同花顺客户端版本不兼容，提供的文件句柄不正确，具体错误为：pywinauto.findwindows.ElementNotFoundError: {'control_id': 1038, 'class_name': 'Static', 'top_level_only': False, 'parent': <win32_element_info.HwndElementInfo - '网上股票交易系统5.0', AfxFrameOrView42s, 723342>, 'backend': 'win32'}，这个错误有时候会出现
4. 获取可用资金时还会出现检测到您正在拷贝数据，为保护您的帐号数据安全，请先输入验证码，这时候程序不会自动输入验证码，导致获取失败

希望楼主提供解决方法，若是版本问题，还望更新客户端软件或者更新程序

**Comment by Sustainedg** [comment]
我也有这个问题，同求

**Comment by qadws007** [comment]
不适合这个版本了

**Comment by leonliu2001** [comment]
有时出现的错误最讨厌，难道句柄号还会变化？
