### ISSUE TITLE
好像“买入”功能失效了。

### ISSUE THREAD

**Issue by scirocc** [nladuo/THSTrader#13]
问题出在这，
self.main_wnd.window(control_id=0x408, class_name="Edit"). .set_text(str(stock_no))  # 设置股票代码
这个元素的定位是成功的，draw_outline()可以正常显示，但set_text后毫无反应

**Comment by ljk99** [comment]
我也碰到这个问题，可以怎么解决呢？

**Comment by ln93** [comment]
最终我用模拟按键的方法选择了选框。不过这样就不太可靠了。
