### ISSUE TITLE
所需依赖的版本问题

### ISSUE THREAD

**Issue by linuxyan** [nladuo/THSTrader#2]
你好， 我今天试了一下你的这个脚本，我是直接pip install requirements.txt 这样安装的依赖，结果发现安装的版本和你代码里面用的很多api都不一样了，希望能在requirements.txt里面标注所依赖的库的版本号，谢谢。 如果想一起交流策略方面的，可以加我QQ：5108926

**Comment by nladuo** [comment]
这个是去年实习的时候写的了，我会抽时间完善一下的。谢谢反馈。我本身不做策略的，只是实习的时候随便跑了跑demo。

linuxyan <notifications@github.com>于2019年2月18日 周一下午10:36写道：

**Comment by nladuo** [comment]
requirements.txt里的内容已经更新了。我试了跑不起来的原因是因为同花顺客户端做了更新。验证码也变了，我会再对项目进行更新。

**Comment by ctrai88** [comment]
用验证码8081去训练发现结果是3081，如何解决？

**Comment by nladuo** [comment]
@ctrai88 验证码现在不能用了。得改。还没改好。

**Comment by ctrai88** [comment]
什么时候改好，可以用验证码呢？

**Comment by nladuo** [comment]
验证码改用tesseract就可以了。不过又有新的bug了。我会抽时间改，最近有点儿忙。

**Comment by nladuo** [comment]
早上改了下，应该可以用了。看下新的README把。
