### ISSUE TITLE
想请教您如何获得control_id

### ISSUE THREAD

**Issue by scirocc** [nladuo/THSTrader#3]
作者您好，我是个私募从业人员，有两个问题想要请教您：
1想请教您如何获得control_id，我在窗口下调用self.main_wnd.print_control_identifiers()发现也无法返回子窗口的control_id
2.获得grid中内容的方法，我看您是用的模拟键盘鼠标，把数据取到剪切板中再进行分析读取；为何无法取得grid的窗口，继而通过窗口继续调取数据？（跳过ocr识别的时间）

**Comment by nladuo** [comment]
问题1：用winspy++这样的软件就可以。
问题2：我记得不好直接拿到grid窗口的数据，或者拿不到grid窗口的数据。只能复制粘贴。（时间隔得比较久了，有些不太记得了。当时是根据easy_trader的代码重构的。easy_trader也是这么做的。）
