### ISSUE TITLE
下载链接的同花顺不升级不能用了，求助

### ISSUE THREAD

**Issue by sanjumsheng** [nladuo/THSTrader#6]
2019-11-15日起
，下载链接里的同花顺客户端不升级不能用了，升级后又复制粘贴不了，求助，谢谢
![11](https://user-images.githubusercontent.com/6977280/68861890-63efcb80-0727-11ea-93e5-45d381ceb061.png)

**Comment by nladuo** [comment]
应该是太久没更新了，我抽时间升级一下API。

**Comment by sanjumsheng** [comment]
好的，谢谢

**Comment by 0JustinTang0** [comment]
兄好，大概什么时候可以升级一下API？

**Comment by nladuo** [comment]
@0JustinTang0 目前暂时没有时间更新这个了，可能得等暑假了。

**Comment by nladuo** [comment]
新版本已更新，换了一个2015年同花顺的客户端，我抽时间录一遍视频，如果视频审核通过后再通知到这里来。

**Comment by nladuo** [comment]
新版本安装使用视频：https://www.bilibili.com/video/av46248487?p=2

**Comment by 0JustinTang0** [comment]
> 新版本已更新，换了一个2015年同花顺的客户端，我抽时间录一遍视频，如果视频审核通过后再通知到这里来。

2015版本的同花顺用不了啊
