### ISSUE TITLE
新版本的支持

### ISSUE THREAD

**Issue by Tu5039** [nladuo/THSTrader#8]
我在您的基础上对8.70版本中使用出现的一些问题做了针对性的修改，但是因为不知道怎么合并到您的分支，所以目前上传到了自己的github：https://github.com/TuJimwel/THSTrader.git，您在合并到这个项目的分支之后我再将我的代码删除

**Comment by nladuo** [comment]
你到我的项目地址，然后提一个PR。应该直接能看到。
